## creating numpy array 

In [1]:
import numpy as np

### 1. converting python list into numpy arrays

In [2]:
myArray = np.array([1,3,4])

In [3]:
print(type(myArray))

<class 'numpy.ndarray'>


In [5]:
myMatrix= [[2,4,6],[7,9,12],[5,1,6]]

In [6]:
np.array(myMatrix)

array([[ 2,  4,  6],
       [ 7,  9, 12],
       [ 5,  1,  6]])

## 2. Using the arange function

In [7]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [10]:
# creating numpy array of zeros as it element
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# creating numpy array of ones as it element
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
#np.linspace to create evenly spaced numbers
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

## numpy random

In [16]:
# populates evenly distributed numbers from [0,1)
np.random.rand(2)

array([0.89745696, 0.27752433])

In [18]:
np.random.randn(3)

array([ 0.87868101, -1.16179971,  0.34201512])

In [19]:
np.random.randint(0,54,3)

array([10, 29,  4])

In [22]:
#seed is used to generate repeated number of random numbers
np.random.seed(42)
np.random.randint(1,54,3)

array([39, 52, 29])

## Reshaping

In [23]:
arr = np.arange(15)

In [25]:
arr.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
intarr=np.random.randint(2,57,10)
intarr

array([40, 20, 24, 12, 12, 25, 54, 37, 41, 25])

In [29]:
intarr.max() # maximum number

54

In [30]:
intarr.min() # min number

12

In [33]:
intarr.shape

(10,)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
arr.reshape(15,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

## ii. Numpy Indexing

In [40]:
arr =np.arange(1,15)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
arr[1:4]

array([2, 3, 4])

In [42]:
arr[5:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

## ii(a) numpy broadcasting

In [45]:
# slicing
sliceArray = np.arange(15)
sliceArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
sliceArray[:] = 34
sliceArray


array([34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34])

In [48]:
# 2d indexing and slicing
two_d = np.arange(1,16).reshape(3,5)

In [49]:
two_d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [53]:
two_d[0,0:3]

array([1, 2, 3])

In [56]:
two_d[0:2,0:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [58]:
# conditional selection
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [60]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])